[authorization_schema]
development         = ["auto", "ask"]
internal_acceptance = ["auto", "ask"]
add                 = ["auto", "ask"]
commit              = ["auto", "ask"]
direct_merge        = ["not_applicable"]
direct_merge_error  = ["not_applicable"]
push                = ["auto", "ask"]
push_error          = ["auto", "ask"]
pr_merge            = ["not_applicable"]
pr_merge_error      = ["not_applicable"]
close_issue         = ["auto", "ask"]
cleanup_sync        = ["auto", "ask"]

[issue_template]
zh-CN = "../../references/issue.zh-CN.json"
en = "../../references/issue.en.json"

[zh-CN]
description = "以 Issue 为依据，在当前工作区的当前分支直接开发、提交并推送。"

[en]
description = ""
