# Read only a launcher generated by GIDD; never evaluate batch text.
function Get-GiddBoundRuntime {
    param([string]$Root, [switch]$KindOnly)
    try {
        $launcher = Join-Path $Root 'js_exec.cmd'
        Assert-GiddPlainPath $launcher
        if (-not [IO.File]::Exists($launcher) -or (Get-Item -LiteralPath $launcher).Length -gt 16384) { return $null }
        $text = [IO.File]::ReadAllText($launcher)
        $lines = @($text -split '\r?\n' | Where-Object { $_ -cmatch '^set "GIDD_JS_EXEC=(.+)"$' })
        if ($lines.Count -ne 1 -or $lines[0] -cnotmatch '^set "GIDD_JS_EXEC=(.+)"$') { return $null }
        $encoded = $Matches[1]; $source = 'path'
        if ($KindOnly) {
            if ($encoded -notmatch '\\(bun|node)\.exe$') { return $null }
            $name = $Matches[1]
            $candidate = @{id="tool.$name";details=@{source='managed'}}
            $normalized = $text.Replace($encoded,"%~dp0$name\$name.exe")
            if ($normalized -ceq (Get-GiddLauncherText $candidate)) { return $candidate }
            return $null
        }
        if ($encoded -cmatch '^%~dp0(bun|node)\\\1\.exe$') {
            $name = $Matches[1]; $path = Join-Path $Root "$name/$name.exe"; $source = 'managed'
        } elseif ($encoded -cmatch '^%~dp0(\.runtime-path-[a-f0-9]{64})\\(bun|node)\.exe$') {
            $linkName = $Matches[1]; $name = $Matches[2]
            $link = Get-Item -LiteralPath (Join-Path $Root $linkName) -Force
            if ($link.LinkType -ne 'Junction' -or @($link.Target).Count -ne 1) { return $null }
            $path = Join-Path ([string]$link.Target[0]) "$name.exe"
        } else {
            $path = $encoded.Replace('%%','%')
            if (-not [IO.Path]::IsPathRooted($path) -or $path -notmatch '\\(bun|node)\.exe$') { return $null }
            $name = $Matches[1]
        }
        $candidate = @{ id="tool.$name"; details=@{path=$path;source=$source} }
        if ($text -cne (Get-GiddLauncherText $candidate) -or -not (Test-GiddRuntimeBinding $Root (Get-GiddRuntimeBinding $candidate))) { return $null }
        return $candidate
    } catch { return $null }
}

function Find-GiddBootstrapRuntime {
    param($Storage, [switch]$Node, [ValidateSet('','bun','node')][string]$Runtime = '')
    if ($Node) { $Runtime = 'node' }
    $bound = Get-GiddBoundRuntime $Storage.tools_root
    if ($bound -and (-not $Runtime -or $bound.id -eq "tool.$Runtime")) {
        $name = $bound.id.Substring(5)
        $owned = $bound.details.source -ne 'managed' -or (Test-GiddManagedTool (Join-Path $Storage.tools_root $name) $name)
        if ($owned) {
            $probe = Invoke-GiddRuntimeCompatibility $bound.details.path $name
            if ($probe.status -eq 'compatible') {
                $candidate = New-Check $bound.id 'ready' 'bound_runtime_compatible' @{path=$bound.details.path;source=$bound.details.source;version=$probe.version;minimum=$probe.minimum;rejected=@()}
                return @{candidate=$candidate;attempts=@($candidate)}
            }
        }
    }
    $order = if ($Runtime) { @($Runtime) } elseif ($Node) { @('node') } else { @('bun','node') }
    $attempts = @()
    foreach ($source in @('managed','path')) {
        foreach ($name in $order) {
            $candidate = Find-Tool $name ([version]'0.0.0') '' (Join-Path $Storage.tools_root "$name/$name.exe") -Source $source -CheckCompatibility
            $attempts += $candidate
            if ($candidate.status -eq 'ready') { return @{ candidate=$candidate; attempts=$attempts } }
        }
    }
    return @{ candidate=$null; attempts=$attempts }
}

function Get-GiddRuntimeBinding {
    param($Candidate)
    if ($Candidate.details.source -eq 'managed' -or $Candidate.details.path -notmatch '[^\x00-\x7f]') { return $null }
    $target = [IO.Path]::GetDirectoryName([IO.Path]::GetFullPath($Candidate.details.path))
    $sha = [Security.Cryptography.SHA256]::Create()
    try { $key = [BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($target))).Replace('-','').ToLowerInvariant() }
    finally { $sha.Dispose() }
    return @{ name='.runtime-path-' + $key; target=$target }
}

function Test-GiddRuntimeBinding {
    param([string]$Root, $Binding)
    if (-not $Binding) { return $true }
    $item = Get-Item -LiteralPath (Join-Path $Root $Binding.name) -Force -ErrorAction SilentlyContinue
    if (-not $item -or -not ($item.Attributes -band [IO.FileAttributes]::ReparsePoint) -or $item.LinkType -ne 'Junction') { return $false }
    return @($item.Target).Count -eq 1 -and [string]::Equals([IO.Path]::GetFullPath([string]$item.Target[0]), $Binding.target, [StringComparison]::OrdinalIgnoreCase)
}

function Write-GiddRuntimeBinding {
    param([string]$Root, $Binding)
    if (-not $Binding) { return }
    Assert-GiddPlainPath $Root
    if (Test-GiddRuntimeBinding $Root $Binding) { return }
    $path = Join-Path $Root $Binding.name
    if (Get-Item -LiteralPath $path -Force -ErrorAction SilentlyContinue) { throw 'occupied_runtime_binding' }
    # This link is installation data, never an owned copy of the external tool.
    # Retain old links: publication may fail and another launcher may still use them.
    [void](New-Item -ItemType Junction -Path $path -Target $Binding.target -ErrorAction Stop)
    if (-not (Test-GiddRuntimeBinding $Root $Binding)) { throw 'runtime_binding_failed' }
}

function Get-GiddLauncherText {
    param($Candidate, [switch]$PreviousFormat)
    $name = $Candidate.id.Substring(5)
    $binding = Get-GiddRuntimeBinding $Candidate
    $executable = if ($Candidate.details.source -eq 'managed') { "%~dp0$name\$name.exe" }
        elseif ($binding) { "%~dp0$($binding.name)\$name.exe" }
        else { $Candidate.details.path.Replace('%','%%') }
    if ($executable -match '["\r\n]') { throw 'invalid_runtime_path' }
    # ASCII source: Unicode paths arrive through cmd's native variable expansion.
    # No CHCP (console side effects), CALL (double expansion), or runtime search.
    return (@(
        '@echo off'
        'setlocal DisableDelayedExpansion'
        if ($PreviousFormat) {
            'for /f "tokens=2 delims=:" %%C in (''"%SystemRoot%\System32\chcp.com"'') do set "GIDD_JS_CODEPAGE=%%C"'
            '"%SystemRoot%\System32\chcp.com" 65001 >nul'
        }
        ('set "GIDD_JS_EXEC=' + $executable + '"')
        if ($PreviousFormat) { '"%SystemRoot%\System32\chcp.com" %GIDD_JS_CODEPAGE% >nul' }
        '"%GIDD_JS_EXEC%" %*'
        'exit /b %ERRORLEVEL%'
        ''
    ) -join "`r`n")
}

function Write-GiddLauncher {
    param([string]$Root, [string]$Text)
    $path = Join-Path $Root 'js_exec.cmd'
    Assert-GiddPlainPath $path
    if ([IO.File]::Exists($path) -and [IO.File]::ReadAllText($path) -ceq $Text) { return 'reused' }
    $temporary = Join-Path $Root ('.js_exec-' + [guid]::NewGuid().ToString() + '.tmp')
    try {
        Write-GiddDurableFile $temporary ([Text.Encoding]::UTF8.GetBytes($Text))
        if ([IO.File]::Exists($path)) { [IO.File]::Replace($temporary,$path,[System.Management.Automation.Language.NullString]::Value) }
        else { [IO.File]::Move($temporary,$path) }
    } finally { if ([IO.File]::Exists($temporary)) { [IO.File]::Delete($temporary) } }
    return 'published'
}

function Restore-GiddInterruptedRuntime {
    param([string]$Root, [string]$Name)
    $backup = Get-GiddRuntimeBackupPath $Root $Name
    if (-not (Test-Path -LiteralPath $backup)) { return }
    if (-not (Test-GiddOwnedRuntime $backup $Name)) { throw "unknown_runtime_backup:$Name" }
    $launcher = Join-Path $Root 'js_exec.cmd'
    Assert-GiddPlainPath $launcher
    $candidate = @{ id="tool.$Name"; details=@{ source='managed' } }
    # PreviousFormat is comparison-only evidence for upgrades with pending cleanup.
    $committedTexts = @((Get-GiddLauncherText $candidate), (Get-GiddLauncherText $candidate -PreviousFormat))
    # The launcher is the durable commit evidence, including an unchanged binding
    # reused during repair. Never undo that state just because cleanup failed.
    if ((Test-GiddManagedTool (Join-Path $Root $Name) $Name) -and
        [IO.File]::Exists($launcher) -and $committedTexts -ccontains [IO.File]::ReadAllText($launcher)) {
        # If cleanup still fails, stop before another installation or launcher
        # switch can obscure this evidence; leave the working runtime intact.
        Remove-GiddRuntimeBackup $Root $Name
        Remove-GiddStage $Root $Name
        return
    }
    Restore-GiddRuntimeBackup $Root $Name
}

function Invoke-GiddBootstrap {
    param($Storage, [switch]$Yes, [switch]$Node, [switch]$Reinstall, [ValidateSet('','bun','node')][string]$Runtime = '')
    if ($Reinstall -and -not $Yes) { throw 'reinstall_requires_yes' }
    $root = $Storage.tools_root; $launcher = Join-Path $root 'js_exec.cmd'
    if ($Node) { $Runtime = 'node' }
    if ($Reinstall -and -not $Runtime) {
        $bound = Get-GiddBoundRuntime $root -KindOnly
        $Runtime = if ($bound) { $bound.id.Substring(5) } else { 'bun' }
    }
    if (-not $Yes) {
        $found = Find-GiddBootstrapRuntime $Storage -Runtime $Runtime
        $matches = $found.candidate -and (Test-GiddRuntimeBinding $root (Get-GiddRuntimeBinding $found.candidate)) -and [IO.File]::Exists($launcher) -and [IO.File]::ReadAllText($launcher) -ceq (Get-GiddLauncherText $found.candidate)
        return @{ schema='gidd.bootstrap/v1';status=$(if ($matches) {'ready'} else {'needs_bootstrap'});read_only=$true;
            runtime=$found.candidate;attempts=$found.attempts;launcher=$launcher;launcher_matches=[bool]$matches }
    }
    $lock = Open-GiddInstallLock $root
    $prepared = $null; $published = $false
    try {
        foreach ($name in @('bun','node')) { Restore-GiddInterruptedRuntime $root $name }
        $found = Find-GiddBootstrapRuntime $Storage -Runtime $Runtime
        $candidate = $found.candidate
        if (-not $candidate -or $Reinstall) {
            $name = if ($Runtime) {$Runtime} else {'bun'}
            $target = Join-Path $root $name
            $replace = Test-Path -LiteralPath $target
            if ($replace -and -not (Test-GiddOwnedRuntime $target $name)) { throw "occupied_or_unknown_target:$name" }
            $manifest = [IO.File]::ReadAllText((Join-Path $PSScriptRoot '../../runtimes.json')) | ConvertFrom-Json
            $pinned = @($manifest.tools | Where-Object name -eq $name) | Select-Object -First 1
            $definition = Resolve-GiddRelease $name $Storage.tools[$name] $pinned
            Write-GiddInstallationGuide $root
            $prepared = $name
            [void](Install-GiddTool $root $definition { param($phase) [Console]::Error.WriteLine("GIDD bootstrap: $phase") } -Replace:$replace -ValidatePayload {
                param($path,$runtimeName)
                if ((Invoke-GiddRuntimeCompatibility $path $runtimeName).status -ne 'compatible') { throw 'runtime_incompatible' }
            })
            $candidate = Find-Tool $name ([version]'0.0.0') '' (Join-Path $target "$name.exe") -Source managed -CheckCompatibility
            if ($candidate.status -ne 'ready') { throw 'bootstrap_runtime_unusable' }
        }
        Write-GiddInstallationGuide $root
        Write-GiddRuntimeBinding $root (Get-GiddRuntimeBinding $candidate)
        $action = Write-GiddLauncher $root (Get-GiddLauncherText $candidate)
        $published = $true; $cleanupPending = $false
        if ($candidate.details.source -eq 'managed') {
            try {
                Remove-GiddRuntimeBackup $root $candidate.id.Substring(5)
                Remove-GiddStage $root $candidate.id.Substring(5)
            } catch {
                $cleanupPending = $true
                [Console]::Error.WriteLine('GIDD bootstrap: launcher published; installation cache cleanup pending.')
            }
        }
        return @{ schema='gidd.bootstrap/v1';status='ready';read_only=$false;runtime=$candidate;attempts=$found.attempts;
            launcher=$launcher;launcher_action=$action;cleanup_pending=$cleanupPending;runtime_action=$(if ($prepared) {'installed'} else {'reused'}) }
    } catch {
        if ($prepared -and -not $published) { Restore-GiddRuntimeBackup $root $prepared }
        throw
    } finally { $lock.Dispose() }
}
